# Quickstart {.unnumbered}

After building the Docker image, you can start the simulator:

1.  From the root directory of the repository, run the following script in your terminal:

    ```bash
    ./ros2_simulator.sh
    ```

2.  Once the simulator starts, it will display the ROS2 topics available in the terminal. You should see an output similar to this:

    ```output
    ==================================================
    🚀 ROS2 Simulation Started Successfully!
    ==================================================

    📡 Available ROS2 Topics:
    ------------------------------
    /mavymini2_01/actuator_cmd
    /mavymini2_01/dvl
    /mavymini2_01/encoders
    /mavymini2_01/gps
    /mavymini2_01/imu
    /mavymini2_01/odometry_sim
    /mavymini_00/actuator_cmd
    /mavymini_00/dvl
    /mavymini_00/encoders
    /mavymini_00/gps
    /mavymini_00/imu
    /mavymini_00/odometry_sim
    /parameter_events
    /rosout
    ```

    To inspect the data published on these topics, follow these steps:

    a. Open a new terminal window.

    b. Enter the Docker container by executing the following command in a new terminal:

    ```bash
    docker exec -it panisim bash
    ```

    c.  Subscribe to a specific topic using the `ros2 topic echo` command. Replace `<topic_name>` with the actual topic you want to inspect.

    ```bash
    ros2 topic echo <topic_name>
    ```

    For example, to view the odometry data for `mavymini_00`, you would use:

    ```bash
    ros2 topic echo /mavymini_00/odometry_sim
    ```

::: callout-note
The specific topic names may vary depending on the agents activated in your `/inputs/simulation_input.yml` configuration file.
:::
