FROM ros:humble

RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository universe
RUN apt-get update
RUN apt-get -y install gcc gfortran git
RUN apt-get -y install python3-pip python3-serial
RUN apt-get -y install libsm6 libxext6 libxrender1 libfontconfig1 libgl1 sudo xauth htop udev
RUN apt-get update --fix-missing
RUN apt-get -y install libboost-all-dev curl
RUN apt-get -y install libasio-dev 
RUN apt-get -y install ros-humble-diagnostic-updater ros-humble-nmea-msgs ros-humble-rtcm-msgs
RUN apt-get update --fix-missing
RUN apt-get -y install ros-humble-rosbridge-server


ENV USERNAME=mavlab
RUN useradd -m $USERNAME && \
       echo "$USERNAME:$USERNAME" | chpasswd && \
       usermod --shell /bin/bash $USERNAME && \
       usermod -aG sudo $USERNAME && \
       usermod -a -G dialout $USERNAME && \
       echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME && \
       chmod 0440 /etc/sudoers.d/$USERNAME

RUN ln -s /usr/bin/python3 /usr/bin/python

USER mavlab
WORKDIR /home/mavlab

RUN curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
  | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
  && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
  | sudo tee /etc/apt/sources.list.d/ngrok.list \
  && sudo apt update \
  && sudo apt install ngrok
RUN ngrok config add-authtoken 2nkKYVS2dtJXp1wxHDJhuqZhu0i_4x64t4Azsx7tSR44CVCu1

COPY requirements_ros2.txt /home/mavlab/
RUN pip install -r requirements_ros2.txt
ENV PATH=$PATH:/home/mavlab/.local/bin

ENV PYTHONPATH=$PYTHONPATH/workspaces/mavalab/ros2_ws/install/mav_simulator/lib/python3.10/site-packages/mav_simulator:/workspaces/mavlab/ros2_ws/install/gnc/lib/python3.10/site-packages/gnc/:/workspaces/mavlab/ros2_ws/install/uwb_driver/lib/python3.10/site-packages/uwb_driver/

RUN echo "source /opt/ros/humble/setup.bash" >> /home/mavlab/.bashrc
RUN echo "alias sros2='source /opt/ros/humble/setup.bash && source /workspaces/mavlab/ros2_ws/install/setup.bash'" >> ~/.bashrc
RUN echo "alias sbg='sros2 && ros2 launch sbg_driver sbg_device_launch.py'" >> ~/.bashrc
RUN echo "alias uwb='sros2 && ros2 run uwb_driver uwb'" >> ~/.bashrc
RUN echo "alias gnc='sros2 && ros2 run gnc gnc'" >> ~/.bashrc
RUN echo "alias mavsim='sros2 && ros2 run mav_simulator simulate'" >> ~/.bashrc
RUN echo "alias ardusimple='sros2 && ros2 launch ublox_gps ublox_gps_node-launch.py'" >> ~/.bashrc

# Setup SBG drivers
COPY sbg_setup.sh /home/mavlab/
RUN ./sbg_setup.sh

# Install NVM and Node.js
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
ENV NVM_DIR=/home/mavlab/.nvm
ENV NODE_VERSION=20.17.0
RUN . "$NVM_DIR/nvm.sh" && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default && \
    npm install -g npm@latest

# Ensure Node.js and NPM are in the PATH
ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
RUN npm install -g localtunnel

# For web application
EXPOSE 9000

# For actuator data transfer from gnc (jeston ROS2) to raspi (raspi ROS1)
EXPOSE 9001

# For encoder data transfer from mav_simulator (jeston ROS2) to raspi (raspi ROS1)
EXPOSE 9002

# For encoder data transfer from raspi (raspi ROS1) to gnc (jetson ROS2)
EXPOSE 9003
